# Azure Virtual Machine Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered Azure VMs
  provider: "azure"
 --}}

{{!-- main.tf --}}
{{#each resources}}
resource "azurerm_linux_virtual_machine" "{{this.name}}" {
  name                = "{{this.name}}"
  resource_group_name = "{{this.resourceGroupName}}"
  location            = "{{this.location}}"
  size                = "{{this.size}}"
  admin_username      = "{{this.adminUsername}}"
  network_interface_ids = {{json this.networkInterfaceIds}}

  {{#if this.adminPassword}}
  admin_password      = var.admin_password
  {{else}}
  admin_ssh_key {
    username   = "{{this.adminUsername}}"
    public_key = file(var.ssh_public_key_path)
  }
  {{/if}}

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = {{this.osDisk.diskSizeGb 128}}
  }

  source_image_reference {
    publisher = "{{this.imageReference.publisher}}"
    offer     = "{{this.imageReference.offer}}"
    sku       = "{{this.imageReference.sku}}"
    version   = "{{this.imageReference.version}}"
  }

  {{#if this.tags}}
  tags = {{json this.tags}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf --}}
variable "admin_password" {
  description = "Admin password for Linux VM (use SSH keys for production)"
  type        = string
  default     = null
  sensitive   = true
}

variable "ssh_public_key_path" {
  description = "Path to SSH public key file"
  type        = string
  default     = "~/.ssh/id_rsa.pub"
}

variable "vm_zone" {
  description = "Availability zone for VM placement"
  type        = string
  default     = null
}

variable "custom_data" {
  description = "Cloud-init script or custom data"
  type        = string
  default     = null
}

variable "tags" {
  description = "Tags to apply to VM resources"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf --}}
output "vm_ids" {
  description = "Azure VM resource IDs"
  value       = [{{#each resources}}azurerm_linux_virtual_machine.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "vm_private_ips" {
  description = "Private IP addresses"
  value       = [{{#each resources}}azurerm_linux_virtual_machine.{{this.name}}.private_ip_address{{#unless @last}}, {{/unless}}{{/each}}]
}

output "vm_public_ips" {
  description = "Public IP addresses (if assigned)"
  value       = [{{#each resources}}azurerm_linux_virtual_machine.{{this.name}}.public_ip_address{{#unless @last}}, {{/unless}}{{/each}}]
}

output "vm_hostnames" {
  description = "VM hostnames"
  value       = [{{#each resources}}azurerm_linux_virtual_machine.{{this.name}}.computer_name{{#unless @last}}, {{/unless}}{{/each}}]
}
