# Azure Load Balancer Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered Azure Load Balancers
  provider: "azure"
--}}

{{!-- main.tf content for Load Balancers --}}
{{#each resources}}
resource "azurerm_lb" "{{this.name}}" {
  name                = "{{this.name}}"
  location            = "{{this.location}}"
  resource_group_name = "{{this.resourceGroupName}}"
  sku                 = "{{this.sku}}"

  {{#if this.frontendIpConfigurations}}
  dynamic "frontend_ip_configuration" {
    for_each = {{json this.frontendIpConfigurations}}
    content {
      name                         = frontend_ip_configuration.value.name
      {{#if frontend_ip_configuration.value.public_ip_address_id}}
      public_ip_address_id         = frontend_ip_configuration.value.public_ip_address_id
      {{/if}}
      {{#if frontend_ip_configuration.value.private_ip_address}}
      private_ip_address           = frontend_ip_configuration.value.private_ip_address
      {{/if}}
      {{#if frontend_ip_configuration.value.subnet_id}}
      subnet_id                    = frontend_ip_configuration.value.subnet_id
      {{/if}}
    }
  }
  {{/if}}

  {{#if this.backendAddressPools}}
  dynamic "backend_address_pool" {
    for_each = {{json this.backendAddressPools}}
    content {
      name = backend_address_pool.value.name
    }
  }
  {{/if}}

  {{#if this.loadBalancingRules}}
  dynamic "load_balancing_rule" {
    for_each = {{json this.loadBalancingRules}}
    content {
      name                           = load_balancing_rule.value.name
      frontend_ip_configuration_name = load_balancing_rule.value.frontendIpConfigurationName
      backend_address_pool_id        = load_balancing_rule.value.backendAddressPoolId
      protocol                       = load_balancing_rule.value.protocol
      frontend_port                  = load_balancing_rule.value.frontendPort
      backend_port                   = load_balancing_rule.value.backendPort
      enable_floating_ip             = {{json load_balancing_rule.value.enableFloatingIP}}
      idle_timeout_in_minutes        = load_balancing_rule.value.idleTimeoutInMinutes
      load_distribution              = load_balancing_rule.value.loadDistribution
      probe_id                       = load_balancing_rule.value.probeId
    }
  }
  {{/if}}

  {{#if this.probes}}
  dynamic "probe" {
    for_each = {{json this.probes}}
    content {
      name              = probe.value.name
      protocol          = probe.value.protocol
      port              = probe.value.port
      request_path      = probe.value.requestPath
      interval_in_seconds = probe.value.intervalInSeconds
      number_of_attempts = probe.value.numberOfAttempts
    }
  }
  {{/if}}

  {{#if this.tags}}
  tags = {{json this.tags}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "load_balancer_name" {
  description = "Load balancer name"
  type        = string
}

variable "resource_group_name" {
  description = "Resource group name"
  type        = string
}

variable "location" {
  description = "Azure region location"
  type        = string
}

variable "sku" {
  description = "Load balancer SKU (Basic or Standard)"
  type        = string
  default     = "Standard"
}

variable "frontend_ip_configuration" {
  description = "Frontend IP configuration object(s)"
  type        = list(object)
  default     = []
}

variable "backend_address_pools" {
  description = "Backend address pool objects"
  type        = list(object)
  default     = []
}

variable "load_balancing_rules" {
  description = "Load balancing rule objects"
  type        = list(object)
  default     = []
}

variable "probes" {
  description = "Probe objects"
  type        = list(object)
  default     = []
}

variable "tags" {
  description = "Tags to apply"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "lb_ids" {
  description = "IDs of the load balancers"
  value       = [{{#each resources}}azurerm_lb.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "lb_names" {
  description = "Names of the load balancers"
  value       = [{{#each resources}}azurerm_lb.{{this.name}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}

output "lb_frontend_ips" {
  description = "Frontend IP addresses"
  value       = flatten([{{#each resources}}{{#each this.frontendIpConfigurations}}azurerm_lb.{{../this.name}}.frontend_ip_configuration[{{@index}}].{{#if public_ip_address_id}}public_ip_address_id{{else}}private_ip_address{{/if}}{{#unless @last}}, {{/unless}}{{/each}}{{/each}}])
}