# Azure Network Security Group Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered Azure NSGs
  provider: "azure"
--}}

{{!-- main.tf content for NSGs --}}
{{#each resources}}
resource "azurerm_network_security_group" "{{this.name}}" {
  name                = "{{this.name}}"
  location            = "{{this.location}}"
  resource_group_name = "{{this.resourceGroupName}}"

  {{#if this.securityRules}}
  dynamic "security_rule" {
    for_each = {{json this.securityRules}}
    content {
      name                       = security_rule.value.name
      priority                   = security_rule.value.priority
      direction                  = security_rule.value.direction
      access                     = security_rule.value.access
      protocol                   = security_rule.value.protocol
      source_port_range          = security_rule.value.sourcePortRange
      destination_port_range     = security_rule.value.destinationPortRange
      source_address_prefix      = security_rule.value.sourceAddressPrefix
      destination_address_prefix = security_rule.value.destinationAddressPrefix
      {{#if security_rule.value.sourceAddressPrefixes}}
      source_address_prefixes    = {{json security_rule.value.sourceAddressPrefixes}}
      {{/if}}
      {{#if security_rule.value.destinationAddressPrefixes}}
      destination_address_prefixes = {{json security_rule.value.destinationAddressPrefixes}}
      {{/if}}
      {{#if security_rule.value.sourceApplicationSecurityGroups}}
      source_application_security_group_ids = {{json security_rule.value.sourceApplicationSecurityGroups}}
      {{/if}}
      {{#if security_rule.value.destinationApplicationSecurityGroups}}
      destination_application_security_group_ids = {{json security_rule.value.destinationApplicationSecurityGroups}}
      {{/if}}
    }
  }
  {{/if}}

  tags = {{json this.tags}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "network_security_group_name" {
  description = "Network security group name"
  type        = string
}

variable "resource_group_name" {
  description = "Resource group name"
  type        = string
}

variable "location" {
  description = "Azure region location"
  type        = string
}

variable "security_rules" {
  description = "List of security rule objects for the NSG"
  type        = list(object)
  default     = []
}

variable "tags" {
  description = "Tags to apply"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "nsg_ids" {
  description = "IDs of the network security groups"
  value       = [{{#each resources}}azurerm_network_security_group.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "nsg_names" {
  description = "Names of the NSGs"
  value       = [{{#each resources}}azurerm_network_security_group.{{this.name}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}