# Azure Virtual Network Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered Azure VNets
  provider: "azure"
 --}}

{{!-- main.tf --}}
{{#each resources}}
resource "azurerm_virtual_network" "{{this.name}}" {
  name                = "{{this.name}}"
  address_space       = {{json this.addressSpace}}
  location            = "{{this.location}}"
  resource_group_name = "{{this.resourceGroupName}}"

  {{#if this.dnsServers}}
  dns_servers = {{json this.dnsServers}}
  {{/if}}

  {{#if this.tags}}
  tags = {{json this.tags}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf --}}
variable "virtual_network_name" {
  description = "Name for the virtual network"
  type        = string
}

variable "resource_group_name" {
  description = "Resource group name"
  type        = string
}

variable "location" {
  description = "Azure region location"
  type        = string
}

variable "address_space" {
  description = "CIDR address blocks for the VNet"
  type        = list(string)
}

variable "dns_servers" {
  description = "List of DNS server IP addresses"
  type        = list(string)
  default     = []
}

variable "tags" {
  description = "Tags to apply to the virtual network"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf --}}
output "vnet_ids" {
  description = "Azure VNet resource IDs"
  value       = [{{#each resources}}azurerm_virtual_network.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "vnet_address_spaces" {
  description = "VNet address spaces"
  value       = [{{#each resources}}azurerm_virtual_network.{{this.name}}.address_space{{#unless @last}}, {{/unless}}{{/each}}]
}

output "vnet_subnet_ids" {
  description = "IDs of subnets within the VNet"
  value       = flatten([{{#each resources}}{{#each this.subnets}}azurerm_subnet.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}{{/each}}])
}
