# Azure SQL Database Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered Azure SQL databases
  provider: "azure"
--}}

{{!-- main.tf content for SQL databases --}}
{{#each resources}}
resource "azurerm_mssql_database" "{{this.name}}" {
  name                = "{{this.name}}"
  resource_group_name = "{{this.resourceGroupName}}"
  server_name         = "{{this.serverName}}"
  location            = "{{this.location}}"
  collation           = "{{this.collation}}"
  max_size_gb         = {{this.maxSizeBytes}}
  read_scale          = {{json this.readScale}}
  zone_redundant      = {{json this.zoneRedundant}}

  {{#if this.tags}}
  tags = {{json this.tags}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "database_name" {
  description = "SQL database name"
  type        = string
}

variable "resource_group_name" {
  description = "Resource group name"
  type        = string
}

variable "server_name" {
  description = "SQL server name"
  type        = string
}

variable "location" {
  description = "Azure region"
  type        = string
}

variable "collation" {
  description = "Database collation"
  type        = string
  default     = "SQL_Latin1_General_CP1_CI_AS"
}

variable "max_size_gb" {
  description = "Maximum database size in GB"
  type        = number
  default     = 5
}

variable "read_scale" {
  description = "Enable read scale-out"
  type        = bool
  default     = false
}

variable "zone_redundant" {
  description = "Enable zone redundancy"
  type        = bool
  default     = false
}

variable "tags" {
  description = "Tags to apply"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "sql_db_ids" {
  description = "IDs of the SQL databases"
  value       = [{{#each resources}}azurerm_mssql_database.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "sql_db_names" {
  description = "Names of the SQL databases"
  value       = [{{#each resources}}azurerm_mssql_database.{{this.name}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}

output "sql_db_server_names" {
  description = "SQL server names"
  value       = [{{#each resources}}azurerm_mssql_database.{{this.name}}.server_name{{#unless @last}}, {{/unless}}{{/each}}]
}