# Azure Storage Account Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered Azure Storage Accounts
  provider: "azure"
 --}}

{{!-- main.tf --}}
{{#each resources}}
resource "azurerm_storage_account" "{{this.name}}" {
  name                     = "{{this.name}}"
  resource_group_name      = "{{this.resourceGroupName}}"
  location                 = "{{this.location}}"
  account_tier             = "{{this.accountTier}}"
  account_replication_type = "{{this.accountReplicationType}}"
  access_tier              = "{{this.accessTier}}"
  enable_https_traffic_only = {{json this.enableHttpsTrafficOnly}}

  {{#if this.blobProperties}}
  blob_properties {
    {{#if this.blobProperties.deleteRetentionPolicy}}
    delete_retention_policy {
      days = {{this.blobProperties.deleteRetentionPolicy.days}}
    }
    {{/if}}
    {{#if this.blobProperties.containerDeleteRetentionPolicy}}
    container_delete_retention_policy {
      days = {{this.blobProperties.containerDeleteRetentionPolicy.days}}
    }
    {{/if}}
  }
  {{/if}}

  {{#if this.tags}}
  tags = {{json this.tags}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf --}}
variable "storage_account_name" {
  description = "Storage account name (3-24 lowercase alphanumeric)"
  type        = string
}

variable "resource_group_name" {
  description = "Resource group name"
  type        = string
}

variable "location" {
  description = "Azure region location"
  type        = string
}

variable "account_tier" {
  description = "Storage tier (Standard, Premium)"
  type        = string
}

variable "account_replication_type" {
  description = "Replication type (LRS, GRS, ZRS, etc.)"
  type        = string
}

variable "access_tier" {
  description = "Access tier (Hot, Cool, Archive)"
  type        = string
  default     = "Hot"
}

variable "enable_https_traffic_only" {
  description = "Require HTTPS for all requests"
  type        = bool
  default     = true
}

variable "blob_delete_retention_days" {
  description = "Days to retain soft-deleted blobs"
  type        = number
  default     = 7
}

variable "tags" {
  description = "Tags to apply to the storage account"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf --}}
output "storage_account_ids" {
  description = "Azure Storage Account resource IDs"
  value       = [{{#each resources}}azurerm_storage_account.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "storage_account_primary_access_keys" {
  description = "Primary access keys (sensitive)"
  value       = [{{#each resources}}azurerm_storage_account.{{this.name}}.primary_access_key{{#unless @last}}, {{/unless}}{{/each}}]
  sensitive   = true
}

output "storage_account_primary_blob_endpoint" {
  description = "Primary blob endpoints"
  value       = [{{#each resources}}azurerm_storage_account.{{this.name}}.primary_blob_endpoint{{#unless @last}}, {{/unless}}{{/each}}]
}
