# Azure Subnet Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered Azure subnets
  provider: "azure"
--}}

{{!-- main.tf content for subnets --}}
{{#each resources}}
resource "azurerm_subnet" "{{this.name}}" {
  name                 = "{{this.name}}"
  resource_group_name  = "{{this.resourceGroupName}}"
  virtual_network_name = "{{this.virtualNetworkName}}"
  address_prefixes     = {{json this.addressPrefixes}}
  {{#if this.serviceEndpoints}}
  service_endpoints    = {{json this.serviceEndpoints}}
  {{/if}}
  {{#if this.delegations}}
  delegations          = {{json this.delegations}}
  {{/if}}
  {{#if this.privateEndpointNetworkPolicies}}
  private_endpoint_network_policies_enabled = {{json this.privateEndpointNetworkPolicies}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "subnet_name" {
  description = "Subnet name"
  type        = string
}

variable "resource_group_name" {
  description = "Resource group name"
  type        = string
}

variable "virtual_network_name" {
  description = "Virtual network name"
  type        = string
}

variable "address_prefixes" {
  description = "CIDR address prefixes for the subnet"
  type        = list(string)
}

variable "service_endpoints" {
  description = "List of service endpoints for the subnet"
  type        = list(string)
  default     = []
}

variable "delegations" {
  description = "List of delegation objects for the subnet"
  type        = list(object)
  default     = []
}

variable "private_endpoint_network_policies_enabled" {
  description = "Enable/disable network policies for private endpoints"
  type        = string
  default     = null
}

{{!-- outputs.tf declarations --}}
output "subnet_ids" {
  description = "IDs of the subnets"
  value       = [{{#each resources}}azurerm_subnet.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "subnet_names" {
  description = "Names of the subnets"
  value       = [{{#each resources}}azurerm_subnet.{{this.name}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}

output "subnet_address_prefixes" {
  description = "Address prefixes of the subnets"
  value       = [{{#each resources}}azurerm_subnet.{{this.name}}.address_prefixes{{#unless @last}}, {{/unless}}{{/each}}]
}