# GCP Persistent Disk Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered GCP Persistent Disks
  provider: "gcp"
--}}

{{!-- main.tf content for disks --}}
{{#each resources}}
resource "google_compute_disk" "{{this.name}}" {
  name  = "{{this.name}}"
  zone  = "{{this.zone}}"
  size  = {{this.size}}
  type  = "{{this.type}}"
  project = var.project

  {{#if this.sourceSnapshot}}
  source_snapshot = "{{this.sourceSnapshot}}"
  {{/if}}

  {{#if this.sourceImage}}
  source_image = "{{this.sourceImage}}"
  {{/if}}

  {{#if this.labels}}
  labels = {{json this.labels}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "disk_name" {
  description = "Disk name"
  type        = string
}

variable "zone" {
  description = "GCP zone"
  type        = string
}

variable "size" {
  description = "Disk size in GB"
  type        = number
}

variable "type" {
  description = "Disk type (pd-standard, pd-ssd, pd-balanced, pd-extreme)"
  type        = string
  default     = "pd-standard"
}

variable "project" {
  description = "GCP project ID"
  type        = string
}

variable "source_snapshot" {
  description = "Snapshot to create disk from"
  type        = string
  default     = null
}

variable "source_image" {
  description = "Image to create disk from"
  type        = string
  default     = null
}

variable "labels" {
  description = "Labels for the disk"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "disk_ids" {
  description = "Disk self-links"
  value       = [{{#each resources}}google_compute_disk.{{this.name}}.self_link{{#unless @last}}, {{/unless}}{{/each}}]
}

output "disk_names" {
  description = "Disk names"
  value       = [{{#each resources}}google_compute_disk.{{this.name}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}