# GCP Cloud Storage Bucket Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered GCP Storage buckets
  provider: "gcp"
--}}

{{!-- main.tf content for storage buckets --}}
{{#each resources}}
resource "google_storage_bucket" "{{this.name}}" {
  name          = "{{this.name}}"
  location      = "{{this.location}}"
  storage_class = "{{this.storageClass}}"
  project       = var.project

  {{#if this.cors}}
  cors = {{json this.cors}}
  {{/if}}

  {{#if this.versioning}}
  versioning {
    enabled = {{json this.versioning.enabled}}
  }
  {{/if}}

  {{#if this.encryption}}
  encryption {
    {{#if this.encryption.defaultKmsKeyName}}
    default_kms_key_name = "{{this.encryption.defaultKmsKeyName}}"
    {{/if}}
  }
  {{/if}}

  {{#if this.labels}}
  labels = {{json this.labels}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "bucket_name" {
  description = "Storage bucket name (globally unique)"
  type        = string
}

variable "location" {
  description = "Bucket location/region"
  type        = string
}

variable "storage_class" {
  description = "Storage class (STANDARD, NEARLINE, COLDLINE, ARCHIVE)"
  type        = string
  default     = "STANDARD"
}

variable "project" {
  description = "GCP project ID"
  type        = string
}

variable "cors" {
  description = "CORS configuration"
  type        = list(object)
  default     = []
}

variable "versioning" {
  description = "Versioning configuration"
  type        = object({
    enabled = bool
  })
  default     = null
}

variable "encryption" {
  description = "Encryption configuration (default KMS key)"
  type        = object({
    default_kms_key_name = string
  })
  default     = null
}

variable "labels" {
  description = "Labels for the bucket"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "bucket_names" {
  description = "Bucket names"
  value       = [{{#each resources}}google_storage_bucket.{{this.name}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}

output "bucket_urls" {
  description = "Bucket URLs"
  value       = [{{#each resources}}google_storage_bucket.{{this.name}}.url{{#unless @last}}, {{/unless}}{{/each}}]
}

output "bucket_self_links" {
  description = "Bucket self-links"
  value       = [{{#each resources}}google_storage_bucket.{{this.name}}.self_link{{#unless @last}}, {{/unless}}{{/each}}]
}