# GCP Compute Instance Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered GCP Compute instances
  provider: "gcp"
 --}}

{{!-- main.tf --}}
{{#each resources}}
resource "google_compute_instance" "{{this.name}}" {
  name         = "{{this.name}}"
  machine_type = "{{this.machineType}}"
  zone         = "{{this.zone}}"

  {{#if this.canIpForward}}
  can_ip_forward = {{json this.canIpForward}}
  {{/if}}

  {{#if this.tags}}
  tags = {{json this.tags}}
  {{/if}}

  boot_disk {
    initialize_params {
      {{#if this.bootDisk.image}}
      image = "{{this.bootDisk.image}}"
      {{else}}
      size  = {{this.bootDisk.sizeGb 50}}
      type  = "{{this.bootDisk.type 'pd-standard'}}"
      {{/if}}
    }
  }

  {{#each this.networkInterfaces}}
  network_interface {
    {{#if this.networkIP}}
    network_ip = "{{this.networkIP}}"
    {{/if}}

    {{#if this.subnetwork}}
    subnetwork = "{{this.subnetwork}}"
    {{/if}}

    {{#if this.accessConfigs}}
    dynamic "access_config" {
      for_each = {{json this.accessConfigs}}
      content {
        nat_ip = access_config.nat_ip
      }
    }
    {{/if}}
  }
  {{/each}}

  {{#if this.metadata}}
  metadata = {
    {{#each this.metadata}}
    {{@key}} = "{{this}}"
    {{/each}}
  }
  {{/if}}
}

{{/each}}

{{!-- variables.tf --}}
variable "instance_name" {
  description = "Instance name"
  type        = string
}

variable "zone" {
  description = "GCP zone"
  type        = string
}

variable "machine_type" {
  description = "Machine type (e.g., e2-micro, e2-standard-2)"
  type        = string
  default     = "e2-micro"
}

variable "project" {
  description = "GCP project ID"
  type        = string
}

variable "network" {
  description = "VPC network name or self_link"
  type        = string
  default     = "default"
}

variable "subnetwork" {
  description = "Subnetwork name or self_link"
  type        = string
  default     = null
}

variable "image" {
  description = "Boot disk image"
  type        = string
  default     = "debian-cloud/debian-12"
}

variable "disk_size_gb" {
  description = "Boot disk size in GB"
  type        = number
  default     = 50
}

variable "disk_type" {
  description = "Boot disk type (pd-standard, pd-ssd, pd-balanced)"
  type        = string
  default     = "pd-standard"
}

variable "ssh_keys" {
  description = "SSH public keys map (username: public_key)"
  type        = map(string)
  default     = {}
}

variable "labels" {
  description = "Resource labels"
  type        = map(string)
  default     = {}
}

variable "metadata" {
  description = "Additional metadata key-value pairs"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf --}}
output "instance_ids" {
  description = "GCE instance IDs"
  value       = [{{#each resources}}google_compute_instance.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "instance_private_ips" {
  description = "Private IP addresses"
  value       = [{{#each resources}}google_compute_instance.{{this.name}}.network_interface[0].network_ip{{#unless @last}}, {{/unless}}{{/each}}]
}

output "instance_public_ips" {
  description = "Public IP addresses (if assigned)"
  value       = [{{#each resources}}google_compute_instance.{{this.name}}.network_interface[0].access_config[0].nat_ip{{#unless @last}}, {{/unless}}{{/each}}]
}

output "instance_self_links" {
  description = "Instance self-links"
  value       = [{{#each resources}}google_compute_instance.{{this.name}}.self_link{{#unless @last}}, {{/unless}}{{/each}}]
}
