# GCP Firewall Rule Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered GCP Firewall rules
  provider: "gcp"
--}}

{{!-- main.tf content for firewall rules --}}
{{#each resources}}
resource "google_compute_firewall" "{{this.name}}" {
  name    = "{{this.name}}"
  network = "{{this.network}}"
  project = var.project

  direction     = "{{this.direction}}"
  priority      = {{this.priority}}
  source_ranges = {{json this.sourceRanges}}
  {{#if this.destinationRanges}}
  destination_ranges = {{json this.destinationRanges}}
  {{/if}}

  {{#if this.allowed}}
  dynamic "allow" {
    for_each = {{json this.allowed}}
    content {
      protocol = allow.value.protocol
      ports    = {{json allow.value.ports}}
    }
  }
  {{/if}}

  {{#if this.denied}}
  dynamic "deny" {
    for_each = {{json this.denied}}
    content {
      protocol = deny.value.protocol
      ports    = {{json deny.value.ports}}
    }
  }
  {{/if}}

  {{#if this.sourceTags}}
  source_tags = {{json this.sourceTags}}
  {{/if}}

  {{#if this.targetTags}}
  target_tags = {{json this.targetTags}}
  {{/if}}

  {{#if this.sourceServiceAccounts}}
  source_service_accounts = {{json this.sourceServiceAccounts}}
  {{/if}}

  {{#if this.targetServiceAccounts}}
  target_service_accounts = {{json this.targetServiceAccounts}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "firewall_name" {
  description = "Firewall rule name"
  type        = string
}

variable "network" {
  description = "VPC network name or self_link"
  type        = string
}

variable "project" {
  description = "GCP project ID"
  type        = string
}

variable "direction" {
  description = "Direction (INGRESS or EGRESS)"
  type        = string
}

variable "priority" {
  description = "Priority (0-65535, lower is higher priority)"
  type        = number
  default     = 1000
}

variable "source_ranges" {
  description = "List of source CIDR ranges"
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

variable "destination_ranges" {
  description = "List of destination CIDR ranges"
  type        = list(string)
  default     = []
}

variable "allowed" {
  description = "List of allowed protocols/ports"
  type        = list(object)
  default     = []
}

variable "denied" {
  description = "List of denied protocols/ports"
  type        = list(object)
  default     = []
}

variable "source_tags" {
  description = "Source tags for targeting"
  type        = list(string)
  default     = []
}

variable "target_tags" {
  description = "Target tags for targeting"
  type        = list(string)
  default     = []
}

variable "source_service_accounts" {
  description = "Source service accounts"
  type        = list(string)
  default     = []
}

variable "target_service_accounts" {
  description = "Target service accounts"
  type        = list(string)
  default     = []
}

{{!-- outputs.tf declarations --}}
output "firewall_self_links" {
  description = "Self-links of firewall rules"
  value       = [{{#each resources}}google_compute_firewall.{{this.name}}.self_link{{#unless @last}}, {{/unless}}{{/each}}]
}

output "firewall_names" {
  description = "Firewall rule names"
  value       = [{{#each resources}}google_compute_firewall.{{this.name}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}