# GCP Load Balancer (Global Address) Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered GCP Global Addresses (Load Balancer IPs)
  provider: "gcp"
--}}

{{!-- main.tf content for global addresses --}}
{{#each resources}}
resource "google_compute_global_address" "{{this.name}}" {
  name       = "{{this.name}}"
  region     = "{{this.region}}"
  ip_version = "{{this.ipVersion}}"
  address_type = "{{this.addressType}}"
  project    = var.project

  {{#if this.address}}
  address = "{{this.address}}"
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "address_name" {
  description = "Global address name"
  type        = string
}

variable "region" {
  description = "GCP region (or use 'global' for some configurations)"
  type        = string
}

variable "ip_version" {
  description = "IP version (IPV4 or IPV6)"
  type        = string
  default     = "IPV4"
}

variable "address_type" {
  description = "Address type (EXTERNAL or INTERNAL)"
  type        = string
  default     = "EXTERNAL"
}

variable "project" {
  description = "GCP project ID"
  type        = string
}

variable "address" {
  description = "Static IP address (optional, will be allocated if omitted)"
  type        = string
  default     = null
}

{{!-- outputs.tf declarations --}}
output "lb_address_self_links" {
  description = "Self-links of global addresses"
  value       = [{{#each resources}}google_compute_global_address.{{this.name}}.self_link{{#unless @last}}, {{/unless}}{{/each}}]
}

output "lb_addresses" {
  description = "IP addresses"
  value       = [{{#each resources}}google_compute_global_address.{{this.name}}.address{{#unless @last}}, {{/unless}}{{/each}}]
}