# GCP VPC Network Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered GCP VPC networks
  provider: "gcp"
 --}}

{{!-- main.tf --}}
{{#each resources}}
resource "google_compute_network" "{{this.name}}" {
  name                    = "{{this.name}}"
  auto_create_subnetworks = {{json this.autoCreateSubnetworks}}
  routing_mode            = "{{this.routingConfig.routingMode}}"
  project                 = var.project

  {{#if this.description}}
  description = "{{this.description}}"
  {{/if}}

  {{#if this.mtu}}
  mtu = {{this.mtu}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf --}}
variable "network_name" {
  description = "VPC network name"
  type        = string
}

variable "project" {
  description = "GCP project ID"
  type        = string
}

variable "auto_create_subnetworks" {
  description = "Automatically create subnetworks (default: true for auto mode, false for custom)"
  type        = bool
  default     = true
}

variable "routing_mode" {
  description = "Routing mode (REGIONAL or GLOBAL)"
  type        = string
  default     = "REGIONAL"
}

variable "description" {
  description = "Network description"
  type        = string
  default     = null
}

variable "mtu" {
  description = "Maximum Transmission Unit in bytes (1300-8896)"
  type        = number
  default     = 1460
}

{{!-- outputs.tf --}}
output "network_ids" {
  description = "GCP network IDs"
  value       = [{{#each resources}}google_compute_network.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "network_self_links" {
  description = "Network self-links"
  value       = [{{#each resources}}google_compute_network.{{this.name}}.self_link{{#unless @last}}, {{/unless}}{{/each}}]
}

output "network_name" {
  description = "Network names"
  value       = [{{#each resources}}google_compute_network.{{this.name}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}
