# GCP Cloud SQL Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered GCP Cloud SQL instances
  provider: "gcp"
 --}}

{{!-- main.tf --}}
{{#each resources}}
resource "google_sql_database_instance" "{{this.name}}" {
  name             = "{{this.name}}"
  database_version = "{{this.databaseVersion}}"
  region           = "{{this.region}}"
  project          = var.project

  settings {
    tier              = "{{this.settings.tier}}"
    activation_policy = "{{this.settings.activationPolicy}}"
    availability_type = "{{this.settings.availabilityType}}"

    ip_configuration {
      {{#if this.settings.ipConfiguration.ipv4Enabled}}
      ipv4_enabled = {{json this.settings.ipConfiguration.ipv4Enabled}}
      {{/if}}

      {{#if this.settings.ipConfiguration.privateNetwork}}
      private_network = "{{this.settings.ipConfiguration.privateNetwork}}"
      {{/if}}

      {{#if this.settings.ipConfiguration.authorizedNetworks}}
      authorized_networks {
        name  = "{{this.settings.ipConfiguration.authorizedNetworks.name}}"
        value = "{{this.settings.ipConfiguration.authorizedNetworks.value}}"
      }
      {{/if}}
    }

    {{#if this.settings.backupConfiguration}}
    backup_configuration {
      enabled            = {{json this.settings.backupConfiguration.enabled}}
      start_time         = "{{this.settings.backupConfiguration.startTime}}"
      location           = "{{this.settings.backupConfiguration.location}}"
      point_in_time_recovery_enabled = {{json this.settings.backupConfiguration.pointInTimeRecoveryEnabled}}
    }
    {{/if}}
  }

  {{#if this.deletionProtection}}
  deletion_protection = {{json this.deletionProtection}}
  {{/if}}
}

{{/each}}

{{!-- variables.tf --}}
variable "instance_name" {
  description = "Cloud SQL instance name"
  type        = string
}

variable "project" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "GCP region for the instance"
  type        = string
}

variable "database_version" {
  description = "Database engine version (POSTGRES_15, MYSQL_8_0, etc.)"
  type        = string
  default     = "POSTGRES_15"
}

variable "tier" {
  description = "Machine tier (db-f1-micro, db-g1-small, etc.)"
  type        = string
  default     = "db-f1-micro"
}

variable "root_password" {
  description = "Root/admin database password"
  type        = string
  sensitive   = true
}

variable "activation_policy" {
  description = "Activation policy (ALWAYS, NEVER, ON_DEMAND)"
  type        = string
  default     = "ALWAYS"
}

variable "availability_type" {
  description = "Availability type (ZONAL, REGIONAL)"
  type        = string
  default     = "ZONAL"
}

variable "private_network" {
  description = "Self-link of the VPC network for private IP"
  type        = string
  default     = null
}

variable "enable_ipv4" {
  description = "Enable public IP addresses"
  type        = bool
  default     = false
}

variable "backup_enabled" {
  description = "Enable automated backups"
  type        = bool
  default     = true
}

variable "backup_start_time" {
  description = "Daily backup start time (HH:MM in UTC)"
  type        = string
  default     = "02:00"
}

variable "deletion_protection" {
  description = "Prevent accidental instance deletion"
  type        = bool
  default     = false
}

{{!-- outputs.tf --}}
output "instance_connections" {
  description = "Cloud SQL instance connection names"
  value       = [{{#each resources}}google_sql_database_instance.{{this.name}}.connection_name{{#unless @last}}, {{/unless}}{{/each}}]
}

output "instance_ip_addresses" {
  description = "Public IP addresses (if enabled)"
  value       = [{{#each resources}}google_sql_database_instance.{{this.name}}.ip_address[0].ip_address{{#unless @last}}, {{/unless}}{{/each}}]
}

output "instance_private_ips" {
  description = "Private IP addresses (if private network configured)"
  value       = [{{#each resources}}google_sql_database_instance.{{this.name}}.private_ip_address{{#unless @last}}, {{/unless}}{{/each}}]
}

output "instance_names" {
  description = "Instance names"
  value       = [{{#each resources}}google_sql_database_instance.{{this.name}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}

output "database_connection_info" {
  description = "Database connection information"
  value = {
    for idx, inst in {{json resources}} :
    idx => {
      connection_name = google_sql_database_instance.inst[0].connection_name
      ip_address      = try(google_sql_database_instance.inst[0].ip_address[0].ip_address, null)
      private_ip      = google_sql_database_instance.inst[0].private_ip_address
      database_version = inst[0].databaseVersion
    }
  }
}
