# GCP Subnetwork Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered GCP Subnetworks
  provider: "gcp"
--}}

{{!-- main.tf content for subnetworks --}}
{{#each resources}}
resource "google_compute_subnetwork" "{{this.name}}" {
  name          = "{{this.name}}"
  region        = "{{this.region}}"
  network       = "{{this.network}}"
  ip_cidr_range = "{{this.ipCidrRange}}"
  private_ip_google_access = {{json this.privateIpGoogleAccess}}
  {{#if this.secondaryIpRanges}}
  secondary_ip_ranges = {{json this.secondaryIpRanges}}
  {{/if}}
  {{#if this.stackType}}
  stack_type = "{{this.stackType}}"
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "subnetwork_name" {
  description = "Subnetwork name"
  type        = string
}

variable "region" {
  description = "GCP region"
  type        = string
}

variable "network" {
  description = "VPC network name or self_link"
  type        = string
}

variable "ip_cidr_range" {
  description = "Primary IP CIDR range"
  type        = string
}

variable "private_ip_google_access" {
  description = "Allow VMs without external IP to access Google APIs"
  type        = bool
  default     = false
}

variable "secondary_ip_ranges" {
  description = "List of secondary IP ranges for aliases"
  type        = list(object)
  default     = []
}

variable "stack_type" {
  description = "Stack type (IPV4_ONLY, IPV4_IPV6, IPV6_ONLY)"
  type        = string
  default     = null
}

{{!-- outputs.tf declarations --}}
output "subnetwork_ids" {
  description = "Self-links of the subnetworks"
  value       = [{{#each resources}}google_compute_subnetwork.{{this.name}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "subnetwork_names" {
  description = "Subnetwork names"
  value       = [{{#each resources}}google_compute_subnetwork.{{this.name}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}

output "subnetwork_ip_cidr_ranges" {
  description = "Primary CIDR ranges"
  value       = [{{#each resources}}google_compute_subnetwork.{{this.name}}.ip_cidr_range{{#unless @last}}, {{/unless}}{{/each}}]
}