# AWS EBS Volume Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered EBS volumes
  provider: "aws"
--}}

{{!-- main.tf content for EBS volumes --}}
{{#each resources}}
resource "aws_ebs_volume" "{{this.tags.Name | default 'volume_' }}{{@index}}" {
  availability_zone = "{{this.availabilityZone}}"
  size              = {{this.size}}
  type              = "{{this.volumeType}}"
  {{#if this.iops}}
  iops              = {{this.iops}}
  {{/if}}
  {{#if this.throughput}}
  throughput        = {{this.throughput}}
  {{/if}}
  encrypted         = {{json this.encrypted}}
  {{#if this.snapshotId}}
  snapshot_id       = "{{this.snapshotId}}"
  {{/if}}

  {{#if this.tags}}
  tags = {
    {{#each this.tags}}
    {{@key}} = "{{this}}"
    {{/each}}
  }
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "availability_zone" {
  description = "Availability zone for the volume"
  type        = string
}

variable "size" {
  description = "Size of the volume in GiB"
  type        = number
}

variable "volume_type" {
  description = "Type of volume (gp2, gp3, io1, io2, sc1, st1)"
  type        = string
  default     = "gp3"
}

variable "iops" {
  description = "IOPS for the volume (required for io1/io2)"
  type        = number
  default     = null
}

variable "throughput" {
  description = "Throughput in MB/s (for gp3)"
  type        = number
  default     = null
}

variable "encrypted" {
  description = "Whether to encrypt the volume"
  type        = bool
  default     = false
}

variable "snapshot_id" {
  description = "Snapshot ID to create from"
  type        = string
  default     = null
}

variable "tags" {
  description = "Tags to apply"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "volume_ids" {
  description = "IDs of the EBS volumes"
  value       = [{{#each resources}}aws_ebs_volume.{{this.tags.Name | default 'volume_' }}{{@index}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "volume_arns" {
  description = "ARNs of the volumes"
  value       = [{{#each resources}}aws_ebs_volume.{{this.tags.Name | default 'volume_' }}{{@index}}.arn{{#unless @last}}, {{/unless}}{{/each}}]
}

output "volume_size" {
  description = "Sizes of the volumes"
  value       = [{{#each resources}}aws_ebs_volume.{{this.tags.Name | default 'volume_' }}{{@index}}.size{{#unless @last}}, {{/unless}}{{/each}}]
}