# EC2 Instance Resource Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered EC2 instances
  provider: "aws"
  moduleName: string
 --}}

{{!-- main.tf content for EC2 --}}
{{#each resources}}
resource "aws_instance" "{{this.tags.Name | default 'instance_' }}{{@index}}" {
  ami           = "{{this.ami}}"
  instance_type = "{{this.instanceType}}"

  {{#if this.keyName}}
  key_name      = "{{this.keyName}}"
  {{/if}}

  {{#if this.subnetId}}
  subnet_id     = "{{this.subnetId}}"
  {{/if}}

  {{#if this.vpcSecurityGroupIds}}
  vpc_security_group_ids = {{json this.vpcSecurityGroupIds}}
  {{/if}}

  {{#if this.tags}}
  tags = {
    {{#each this.tags}}
    {{@key}} = "{{this}}"
    {{/each}}
  }
  {{/if}}

  {{#if this.userData}}
  user_data = <<EOF
{{this.userData}}
EOF
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "instance_type" {
  description = "EC2 instance type (e.g., t3.micro, t3.medium)"
  type        = string
  default     = "t3.micro"
}

variable "ami_id" {
  description = "Amazon Machine Image ID to use for the instance"
  type        = string
}

variable "key_name" {
  description = "SSH key pair name"
  type        = string
  default     = null
}

variable "vpc_security_group_ids" {
  description = "List of security group IDs to associate with"
  type        = list(string)
  default     = []
}

variable "subnet_id" {
  description = "Subnet ID to launch the instance in"
  type        = string
}

variable "tags" {
  description = "Tags to apply to the instance"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "instance_ids" {
  description = "IDs of the created EC2 instances"
  value       = [{{#each resources}}aws_instance.{{this.tags.Name | default 'instance_' }}{{@index}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "instance_private_ips" {
  description = "Private IP addresses of the instances"
  value       = [{{#each resources}}aws_instance.{{this.tags.Name | default 'instance_' }}{{@index}}.private_ip{{#unless @last}}, {{/unless}}{{/each}}]
}

output "instance_public_ips" {
  description = "Public IP addresses (if assigned)"
  value       = [{{#each resources}}aws_instance.{{this.tags.Name | default 'instance_' }}{{@index}}.public_ip{{#unless @last}}, {{/unless}}{{/each}}]
}
