# AWS Load Balancer Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered load balancers
  provider: "aws"
--}}

{{!-- main.tf content for load balancers --}}
{{#each resources}}
resource "aws_lb" "{{this.tags.Name | default 'lb_' }}{{@index}}" {
  name               = "{{this.name}}"
  internal           = {{json this.internal}}
  load_balancer_type = "{{this.type}}"
  vpc_id             = "{{this.vpcId}}"
  subnet_ids         = {{json this.subnetIds}}
  security_groups   = {{json this.securityGroups}}

  {{#if this.enableDeletionProtection}}
  enable_deletion_protection = {{json this.enableDeletionProtection}}
  {{/if}}

  {{#if this.tags}}
  tags = {
    {{#each this.tags}}
    {{@key}} = "{{this}}"
    {{/each}}
  }
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "name" {
  description = "Load balancer name"
  type        = string
}

variable "internal" {
  description = "Whether the load balancer is internal"
  type        = bool
  default     = false
}

variable "load_balancer_type" {
  description = "Type of load balancer (application, network, gateway)"
  type        = string
  default     = "application"
}

variable "vpc_id" {
  description = "VPC ID for the load balancer"
  type        = string
}

variable "subnet_ids" {
  description = "List of subnet IDs for the load balancer"
  type        = list(string)
}

variable "security_groups" {
  description = "List of security group IDs"
  type        = list(string)
  default     = []
}

variable "enable_deletion_protection" {
  description = "Enable deletion protection"
  type        = bool
  default     = false
}

variable "tags" {
  description = "Tags to apply"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "lb_ids" {
  description = "IDs of the load balancers"
  value       = [{{#each resources}}aws_lb.{{this.tags.Name | default 'lb_' }}{{@index}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "lb_dns_names" {
  description = "DNS names of the load balancers"
  value       = [{{#each resources}}aws_lb.{{this.tags.Name | default 'lb_' }}{{@index}}.dns_name{{#unless @last}}, {{/unless}}{{/each}}]
}

output "lb_arns" {
  description = "ARNs of the load balancers"
  value       = [{{#each resources}}aws_lb.{{this.tags.Name | default 'lb_' }}{{@index}}.arn{{#unless @last}}, {{/unless}}{{/each}}]
}