# AWS IAM Role Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered IAM roles
  provider: "aws"
--}}

{{!-- main.tf content for IAM roles --}}
{{#each resources}}
resource "aws_iam_role" "{{this.tags.Name | default 'role_' }}{{@index}}" {
  name                = "{{this.name}}"
  path                = "{{this.path}}"
  description         = "{{this.description}}"
  assume_role_policy  = {{json this.assumeRolePolicyDocument}}
  {{#if this.maxSessionDuration}}
  max_session_duration = {{this.maxSessionDuration}}
  {{/if}}

  {{#if this.tags}}
  tags = {
    {{#each this.tags}}
    {{@key}} = "{{this}}"
    {{/each}}
  }
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "name" {
  description = "IAM role name"
  type        = string
}

variable "path" {
  description = "Path for the role"
  type        = string
  default     = "/"
}

variable "description" {
  description = "Role description"
  type        = string
  default     = null
}

variable "assume_role_policy" {
  description = "Assume role policy document (JSON)"
  type        = string
}

variable "max_session_duration" {
  description = "Maximum session duration in seconds (3600-43200)"
  type        = number
  default     = 3600
}

variable "tags" {
  description = "Tags to apply"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "role_arns" {
  description = "ARNs of the IAM roles"
  value       = [{{#each resources}}aws_iam_role.{{this.tags.Name | default 'role_' }}{{@index}}.arn{{#unless @last}}, {{/unless}}{{/each}}]
}

output "role_names" {
  description = "Names of the IAM roles"
  value       = [{{#each resources}}aws_iam_role.{{this.tags.Name | default 'role_' }}{{@index}}.name{{#unless @last}}, {{/unless}}{{/each}}]
}

output "role_paths" {
  description = "Paths of the IAM roles"
  value       = [{{#each resources}}aws_iam_role.{{this.tags.Name | default 'role_' }}{{@index}}.path{{#unless @last}}, {{/unless}}{{/each}}]
}