# RDS Database Instance Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered RDS instances
  provider: "aws"
 --}}

{{!-- main.tf --}}
{{#each resources}}
resource "aws_db_instance" "{{this.tags.Name | default 'db_' }}{{@index}}" {
  identifier              = "{{this.DBInstanceIdentifier}}"
  engine                  = "{{this.engine}}"
  engine_version          = "{{this.engineVersion}}"
  instance_class          = "{{this.DBInstanceClass}}"
  allocated_storage       = {{this.allocatedStorage}}
  storage_type            = "{{this.storageType}}"
  username                = var.db_username
  password                = var.db_password
  skip_final_snapshot     = var.skip_final_snapshot

  {{#if this.dbSubnetGroupId}}
  db_subnet_group_name    = "{{this.dbSubnetGroupId}}"
  {{/if}}

  {{#if this.vpcSecurityGroups}}
  vpc_security_group_ids = {{json this.vpcSecurityGroups}}
  {{/if}}

  {{#if this.multiAz}}
  multi_az                = {{json this.multiAz}}
  {{/if}}

  {{#if this.publiclyAccessible}}
  publicly_accessible     = {{json this.publiclyAccessible}}
  {{/if}}

  backup_retention_period = var.backup_retention_period
  backup_window           = var.backup_window
  maintenance_window     = var.maintenance_window

  {{#if this.tags}}
  tags = {
    {{#each this.tags}}
    {{@key}} = "{{this}}"
    {{/each}}
  }
  {{/if}}
}

{{/each}}

{{!-- variables.tf --}}
variable "db_username" {
  description = "Database admin username"
  type        = string
}

variable "db_password" {
  description = "Database admin password"
  type        = string
  sensitive   = true
}

variable "skip_final_snapshot" {
  description = "Skip final snapshot before destruction"
  type        = bool
  default     = true
}

variable "backup_retention_period" {
  description = "Days to retain backups"
  type        = number
  default     = 7
}

variable "backup_window" {
  description = "Daily backup window (HH:MM-HH:MM)"
  type        = string
  default     = "03:00-04:00"
}

variable "maintenance_window" {
  description = "Weekly maintenance window (Day:HH:MM-Day:HH:MM)"
  type        = string
  default     = "sun:04:00-sun:05:00"
}

{{!-- outputs.tf --}}
output "db_instance_ids" {
  description = "RDS instance identifiers"
  value       = [{{#each resources}}aws_db_instance.{{this.tags.Name | default 'db_' }}{{@index}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "db_endpoints" {
  description = "RDS endpoint addresses"
  value       = [{{#each resources}}aws_db_instance.{{this.tags.Name | default 'db_' }}{{@index}}.address{{#unless @last}}, {{/unless}}{{/each}}]
}

output "db_ports" {
  description = "RDS ports"
  value       = [{{#each resources}}aws_db_instance.{{this.tags.Name | default 'db_' }}{{@index}}.port{{#unless @last}}, {{/unless}}{{/each}}]
}

output "db_arn" {
  description = "RDS instance ARNs"
  value       = [{{#each resources}}aws_db_instance.{{this.tags.Name | default 'db_' }}{{@index}}.arn{{#unless @last}}, {{/unless}}{{/each}}]
}
