# S3 Bucket Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered S3 buckets
  provider: "aws"
 --}}

{{!-- main.tf --}}
{{#each resources}}
resource "aws_s3_bucket" "{{this.bucket}}" {
  bucket = "{{this.bucket}}"

  {{#if this.region}}
  # Region is set by provider configuration
  {{/if}}
}

{{#if resources.[0].versioningConfig}}
resource "aws_s3_bucket_versioning" "{{this.bucket}}" {
  bucket = aws_s3_bucket.{{this.bucket}}.id
  versioning_configuration {
    status = "{{#if this.versioningConfig.Status}}{{this.versioningConfig.Status}}{{else}}Disabled{{/if}}"
  }
}
{{/if}}

{{#if resources.[0].encryption}}
resource "aws_s3_bucket_server_side_encryption_configuration" "{{this.bucket}}" {
  bucket = aws_s3_bucket.{{this.bucket}}.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "{{this.encryption.sseAlgorithm | default 'AES256'}}"
      {{#if this.encryption.kmsKeyId}}
      kms_key_id   = "{{this.encryption.kmsKeyId}}"
      {{/if}}
    }
    bucket_key_enabled = {{json this.encryption.bucketKeyEnabled false}}
  }
}
{{/if}}

{{#if resources.[0].publicAccessBlock}}
resource "aws_s3_bucket_public_access_block" "{{this.bucket}}" {
  bucket = aws_s3_bucket.{{this.bucket}}.id

  block_public_acls       = {{json this.publicAccessBlock.blockPublicAcls true}}
  block_public_policy     = {{json this.publicAccessBlock.blockPublicPolicy true}}
  ignore_public_acls      = {{json this.publicAccessBlock.ignorePublicAcls true}}
  restrict_public_buckets = {{json this.publicAccessBlock.restrictPublicBuckets true}}
}
{{/if}}

{{#if this.tags}}
resource "aws_s3_bucket_tagging" "{{this.bucket}}" {
  bucket = aws_s3_bucket.{{this.bucket}}.id
  tag_set {
    dynamic "tag" {
      for_each = {{json this.tags}}
      content {
        key   = tag.key
        value = tag.value
      }
    }
  }
}
{{/if}}

{{/each}}

{{!-- variables.tf --}}
variable "bucket_acl" {
  description = "Canned ACL to apply (private, public-read, etc.)"
  type        = string
  default     = "private"
}

variable "force_destroy" {
  description = "Allow bucket deletion even when containing objects"
  type        = bool
  default     = false
}

variable "versioning_enabled" {
  description = "Enable S3 versioning"
  type        = bool
  default     = false
}

variable "sse_algorithm" {
  description = "Server-side encryption algorithm (AES256, aws:kms)"
  type        = string
  default     = "AES256"
}

variable "kms_key_id" {
  description = "KMS Key ID for SSE-KMS encryption"
  type        = string
  default     = null
}

variable "tags" {
  description = "Tags to apply to the bucket"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf --}}
output "bucket_ids" {
  description = "S3 bucket IDs (names)"
  value       = [{{#each resources}}aws_s3_bucket.{{this.bucket}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "bucket_arns" {
  description = "S3 bucket ARNs"
  value       = [{{#each resources}}aws_s3_bucket.{{this.bucket}}.arn{{#unless @last}}, {{/unless}}{{/each}}]
}

output "bucket_domain_names" {
  description = "S3 bucket domain names"
  value       = [{{#each resources}}aws_s3_bucket.{{this.bucket}}.bucket_domain_name{{#unless @last}}, {{/unless}}{{/each}}]
}

output "bucket_regional_domain_names" {
  description = "Regional bucket domain names"
  value       = [{{#each resources}}aws_s3_bucket.{{this.bucket}}.bucket_regional_domain_name{{#unless @last}}, {{/unless}}{{/each}}]
}
