# AWS Security Group Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered security groups
  provider: "aws"
--}}

{{!-- main.tf content for security groups --}}
{{#each resources}}
resource "aws_security_group" "{{this.tags.Name | default 'sg_' }}{{@index}}" {
  name        = "{{this.groupName}}"
  description = "{{this.description}}"
  vpc_id      = "{{this.vpcId}}"

  {{#if this.ip_permissions}}
  dynamic "ingress" {
    for_each = {{json this.ip_permissions}}
    content {
      from_port   = ingress.value.fromPort
      to_port     = ingress.value.toPort
      protocol    = ingress.value.ipProtocol
      {{#if ingress.value.cidrBlocks}}
      cidr_blocks = {{json ingress.value.cidrBlocks}}
      {{/if}}
      {{#if ingress.value.ipv6Ranges}}
      ipv6_cidr_blocks = {{json ingress.value.ipv6Ranges}}
      {{/if}}
      {{#if ingress.value.prefixListIds}}
      prefix_list_ids = {{json ingress.value.prefixListIds}}
      {{/if}}
      {{#if ingress.value.userIdGroupPairs}}
      security_groups = {{json (pluck ingress.value.userIdGroupPairs 'groupId')}}
      {{/if}}
    }
  }
  {{/if}}

  {{#if this.ip_permissions_egress}}
  dynamic "egress" {
    for_each = {{json this.ip_permissions_egress}}
    content {
      from_port   = egress.value.fromPort
      to_port     = egress.value.toPort
      protocol    = egress.value.ipProtocol
      {{#if egress.value.cidrBlocks}}
      cidr_blocks = {{json egress.value.cidrBlocks}}
      {{/if}}
      {{#if egress.value.ipv6Ranges}}
      ipv6_cidr_blocks = {{json egress.value.ipv6Ranges}}
      {{/if}}
      {{#if egress.value.prefixListIds}}
      prefix_list_ids = {{json egress.value.prefixListIds}}
      {{/if}}
      {{#if egress.value.userIdGroupPairs}}
      security_groups = {{json (pluck egress.value.userIdGroupPairs 'groupId')}}
      {{/if}}
    }
  }
  {{/if}}

  tags = {
    {{#each this.tags}}
    {{@key}} = "{{this}}"
    {{/each}}
  }
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "name" {
  description = "Security group name"
  type        = string
}

variable "description" {
  description = "Security group description"
  type        = string
  default     = null
}

variable "vpc_id" {
  description = "VPC ID for the security group"
  type        = string
}

variable "ingress" {
  description = "List of ingress rules (objects with fromPort, toPort, ipProtocol, cidrBlocks, etc.)"
  type        = list(object)
  default     = []
}

variable "egress" {
  description = "List of egress rules"
  type        = list(object)
  default     = []
}

variable "tags" {
  description = "Tags to apply"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "security_group_ids" {
  description = "IDs of the created security groups"
  value       = [{{#each resources}}aws_security_group.{{this.tags.Name | default 'sg_' }}{{@index}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "security_group_arns" {
  description = "ARNs of the security groups"
  value       = [{{#each resources}}aws_security_group.{{this.tags.Name | default 'sg_' }}{{@index}}.arn{{#unless @last}}, {{/unless}}{{/each}}]
}

output "security_group_vpc_id" {
  description = "VPC ID of the security groups"
  value       = [{{#each resources}}aws_security_group.{{this.tags.Name | default 'sg_' }}{{@index}}.vpc_id{{#unless @last}}, {{/unless}}{{/each}}]
}