# AWS Subnet Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered subnets
  provider: "aws"
--}}

{{!-- main.tf content for subnets --}}
{{#each resources}}
resource "aws_subnet" "{{this.tags.Name | default 'subnet_' }}{{@index}}" {
  vpc_id            = "{{this.vpcId}}"
  cidr_block        = "{{this.cidrBlock}}"
  availability_zone = "{{this.availabilityZone}}"
  map_public_ip_on_launch = {{json this.mapPublicIpOnLaunch}}

  {{#if this.tags}}
  tags = {
    {{#each this.tags}}
    {{@key}} = "{{this}}"
    {{/each}}
  }
  {{/if}}
}

{{/each}}

{{!-- variables.tf declarations --}}
variable "vpc_id" {
  description = "VPC ID to create the subnet in"
  type        = string
}

variable "cidr_block" {
  description = "CIDR block for the subnet"
  type        = string
}

variable "availability_zone" {
  description = "Availability zone for the subnet"
  type        = string
  default     = null
}

variable "map_public_ip_on_launch" {
  description = "Map public IP on launch for instances in this subnet"
  type        = bool
  default     = false
}

variable "tags" {
  description = "Tags to apply to the subnet"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf declarations --}}
output "subnet_ids" {
  description = "IDs of the created subnets"
  value       = [{{#each resources}}aws_subnet.{{this.tags.Name | default 'subnet_' }}{{@index}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "subnet_cidr_blocks" {
  description = "CIDR blocks of the subnets"
  value       = [{{#each resources}}aws_subnet.{{this.tags.Name | default 'subnet_' }}{{@index}}.cidr_block{{#unless @last}}, {{/unless}}{{/each}}]
}

output "subnet_availability_zones" {
  description = "Availability zones of the subnets"
  value       = [{{#each resources}}aws_subnet.{{this.tags.Name | default 'subnet_' }}{{@index}}.availability_zone{{#unless @last}}, {{/unless}}{{/each}}]
}