# VPC Resource Template
# Generated by tf-module-generator

{{!-- Expected context:
  resources: array of discovered VPCs
  provider: "aws"
 --}}

{{!-- main.tf content --}}
{{#each resources}}
resource "aws_vpc" "{{this.tags.Name | default 'vpc_' }}{{@index}}" {
  cidr_block           = "{{this.cidrBlock}}"
  instance_tenancy     = "{{this.instanceTenancy}}"
  enable_dns_hostnames = {{json this.enableDnsHostnames}}
  enable_dns_support   = {{json this.enableDnsSupport}}

  {{#if this.tags}}
  tags = {
    {{#each this.tags}}
    {{@key}} = "{{this}}"
    {{/each}}
  }
  {{/if}}
}

{{/each}}

{{!-- variables.tf --}}
variable "cidr_block" {
  description = "CIDR block for the VPC"
  type        = string
}

variable "instance_tenancy" {
  description = "Instance tenancy (default, dedicated, host)"
  type        = string
  default     = "default"
}

variable "enable_dns_hostnames" {
  description = "Enable DNS hostnames in the VPC"
  type        = bool
  default     = true
}

variable "enable_dns_support" {
  description = "Enable DNS support in the VPC"
  type        = bool
  default     = true
}

variable "tags" {
  description = "Tags to apply to the VPC"
  type        = map(string)
  default     = {}
}

{{!-- outputs.tf --}}
output "vpc_ids" {
  description = "IDs of the created VPCs"
  value       = [{{#each resources}}aws_vpc.{{this.tags.Name | default 'vpc_' }}{{@index}}.id{{#unless @last}}, {{/unless}}{{/each}}]
}

output "vpc_cidr_blocks" {
  description = "CIDR blocks of the VPCs"
  value       = [{{#each resources}}aws_vpc.{{this.tags.Name | default 'vpc_' }}{{@index}}.cidr_block{{#unless @last}}, {{/unless}}{{/each}}]
}

output "vpc_default_route_table_id" {
  description = "Default route table ID for first VPC"
  value       = aws_vpc.{{lookup (first resources) 'tags' 'Name' 'vpc_0'}}.default_route_table_id
}
